#!name=苹果APNs推送
#!desc=设置完之后要开关飞行模式，断掉所有连接才会生效,如果还是不行可以尝试到设置，隧道，打开包含所有网络，apns开关

[Rule]
DOMAIN-SUFFIX,push.apple.com,节点选择
DOMAIN-SUFFIX,akadns.net,节点选择
DOMAIN-KEYWORD,apple.com.edgekey.net,节点选择
IP-CIDR,17.249.0.0/16,节点选择,no-resolve
IP-CIDR,17.252.0.0/16,节点选择,no-resolve
IP-CIDR,17.57.144.0/22,节点选择,no-resolve
IP-CIDR,17.188.128.0/18,节点选择,no-resolve
IP-CIDR,17.188.20.0/23,节点选择,no-resolve
IP-CIDR6,2620:149:a44::/48,节点选择,no-resolve
IP-CIDR6,2403:300:a42::/48,节点选择,no-resolve
IP-CIDR6,2403:300:a51::/48,节点选择,no-resolve
IP-CIDR6,2a01:b740:a42::/48,节点选择,no-resolve
